export type TechStackSource = {
  name: string;
  type: "frontEnd" | "backEnd" | "other" | "deployment";
  category: "language" | "framework" | "library" | "database" | "tool" | "other";
  yearsExperience: number;
  src: string;
};

export const techStackSources: Record<string, TechStackSource> = {
  javaScript: {
    name: "JavaScript",
    type: "frontEnd",
    category: "language",
    yearsExperience: 4,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg",
  },
  typeScript: {
    name: "TypeScript",
    type: "frontEnd",
    category: "language",
    yearsExperience: 1,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg",
  },
  html: {
    name: "HTML",
    type: "frontEnd",
    category: "language",
    yearsExperience: 4,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg",
  },
  css: {
    name: "CSS",
    type: "frontEnd",
    category: "language",
    yearsExperience: 4,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg",
  },
  python: {
    name: "Python",
    type: "backEnd",
    category: "language",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg",
  },
  sql: {
    name: "SQL",
    type: "backEnd",
    category: "language",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/azuresqldatabase/azuresqldatabase-original.svg",
  },
  php: {
    name: "PHP",
    type: "backEnd",
    category: "language",
    yearsExperience: 2,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg",
  },
  react: {
    name: "React",
    type: "frontEnd",
    category: "library",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
  },
  redux: {
    name: "Redux",
    type: "frontEnd",
    category: "library",
    yearsExperience: 2,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redux/redux-original.svg",
  },
  reduxToolkit: {
    name: "Redux Toolkit",
    type: "frontEnd",
    category: "library",
    yearsExperience: 2,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redux/redux-original.svg",
  },
  contextApi: {
    name: "Context API",
    type: "frontEnd",
    category: "library",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg",
  },
  reactRouter: {
    name: "React Router",
    type: "frontEnd",
    category: "library",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/reactrouter/reactrouter-original.svg",
  },
  jQuery: {
    name: "jQuery",
    type: "frontEnd",
    category: "library",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-plain.svg",
  },
  nextJs: {
    name: "Next.js",
    type: "frontEnd",
    category: "framework",
    yearsExperience: 2,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg",
  },
  bootstrap: {
    name: "Bootstrap",
    type: "frontEnd",
    category: "framework",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original.svg",
  },
  reactBootstrap: {
    name: "React Bootstrap",
    type: "frontEnd",
    category: "library",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/reactbootstrap/reactbootstrap-original.svg",
  },
  flask: {
    name: "Flask",
    type: "backEnd",
    category: "framework",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/flask/flask-original.svg",
  },
  sqlAlchemy: {
    name: "SQLAlchemy",
    type: "backEnd",
    category: "library",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sqlalchemy/sqlalchemy-original.svg",
  },
  postgres: {
    name: "PostgreSQL",
    type: "backEnd",
    category: "database",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg",
  },
  mySql: {
    name: "MySQL",
    type: "backEnd",
    category: "database",
    yearsExperience: 2,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg",
  },
  aws: {
    name: "AWS",
    type: "other",
    category: "database",
    yearsExperience: 2,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg",
  },
  socketIo: {
    name: "Socket.IO",
    type: "backEnd",
    category: "library",
    yearsExperience: 1,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/socketio/socketio-original.svg",
  },
  git: {
    name: "Git",
    type: "other",
    category: "tool",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg",
  },
  gitHub: {
    name: "GitHub",
    type: "other",
    category: "tool",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg",
  },
  // vsCode: {
  //   name: "VS Code",
  //   type: "other",
  //   category: "other",
  //   yearsExperience: 4,
  //   src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg",
  // },
  ubuntu: {
    name: "Ubuntu",
    type: "other",
    category: "tool",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/ubuntu/ubuntu-original.svg",
  },
  railway: {
    name: "Railway",
    type: "deployment",
    category: "other",
    yearsExperience: 1,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/railway/railway-original.svg",
  },
  vercel: {
    name: "Vercel",
    type: "deployment",
    category: "other",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vercel/vercel-original.svg",
  },
  render: {
    name: "Render",
    type: "deployment",
    category: "other",
    yearsExperience: 3,
    // src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/render/render-original.svg",
    src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAAAAADFHGIkAAAAfklEQVR4AWP4jwOgSfzY1D31JhaJU6oMQBDwEl3iiQADGKj+QJMIYICCOlSJlwwwYIoqsYkBDlAl0uHiAigSTzjhEpHIEj+s4eKcF5EknpgibNgE9keddcvq/ZvyOcFKre3t7dNv/odIIFSm/4DoRpcQA/KxSlgPaQlUQFgCABOfchUR/bqdAAAAAElFTkSuQmCC",
  },
  firebase: {
    name: "Firebase",
    type: "deployment",
    category: "other",
    yearsExperience: 3,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebase/firebase-original.svg",
  },
  vite: {
    name: "Vite",
    type: "other",
    category: "tool",
    yearsExperience: 1,
    src: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg",
  },

};
